# This is an action definition file, which has three parts: the goal, the
# result, and the feedback.
#
# Part 1: the goal, to be sent by the client
#
# The movement command
bool stop_requested
---
# Part 2: the result, to be sent by the server upon completion
# Has the move order been executed
bool movement_executed
---
# Part 3: the feedback, to be sent periodically by the server during
# execution.
#
# Has the move order been executed
bool movement_executed